# 変更がかかるファイルを定義
targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/data/*/*.dart
            - lib/presentation/pages/*/*.dart
            - lib/presentation/pages/components/*/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/data/entities/*.dart
        options:
          checked: true
          field_rename: snake # デフォルトから変更
          explicit_to_json: true # ネストしたモデルを toJson できるようにする https://github.com/rrousselGit/freezed/issues/86#issuecomment-593936459