name: CI

# ワークフロー起動条件を定義する
on:
  # プルリクエストが作成 or 更新された時
  pull_request:
    types:
      - opened
      - synchronize

  push:
    branches:
      - main
      - pharmacy

  workflow_dispatch:

jobs:
  analyze_tests:
    name: analyze and test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # ソースコードをチェックアウト
      - name: Checkout
        uses: actions/checkout@v3

      # fvm のバージョンとチャネルを環境変数に設定する
      - name: Check fvm
        uses: kuhnroyal/flutter-fvm-config-action@v1
      # Flutter SDK の設定
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.5.0
        with:
          # バージョンとチャネルは fvm の値を使う
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          # 次回以降起動を速くするためにキャッシュしておく
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
      # flutter pub get を実行
      - name: Install flutter dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze --no-fatal-infos > flutter_analyze_report.txt # info レベルで落ちないようにする
      - name: Format Analyze
        run: dart format --dry-run --set-exit-if-changed .
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"

      - name: Setup danger
        run: |
          gem install bundler
          bundle install
      - name: execute danger
        uses: MeilCli/danger-action@v5
        with:
          plugins_file: "Gemfile"
          install_path: "vendor/bundle"
          danger_file: "Dangerfile"
          danger_id: "danger-pr"
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Flutter test
      # - name: Test
      #   run: |
      #     flutter test --machine > test_report.log
      # - name: Test Report
      #   uses: dorny/test-reporter@v1
      #   if: always()
      #   with:
      #     name: "flutter test"
      #     path: "test_report.log"
      #     reporter: "flutter-json"
      #     fail-on-error: "false"
      #     list-suites: "all"
      #     list-tests: "all"
      #     max-annotations: "30"
